{{- if .Values.wings.enabled -}}
# Headless service for StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pterodactyl.wings.name" . }}-headless
  namespace: {{ .Values.namespace | default "pterodactyl" }}
  labels:
    {{- include "pterodactyl.labels" . | nindent 4 }}
    app.kubernetes.io/component: wings
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    {{- include "pterodactyl.wings.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 443
      targetPort: http
    - name: sftp
      protocol: TCP
      port: 2022
      targetPort: sftp
---
# Individual services for each Wings instance using pod name selector
{{- range $index, $server := .Values.wings.servers }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pterodactyl.wings.name" $ }}-{{ $index }}
  namespace: {{ $.Values.namespace | default "pterodactyl" }}
  labels:
    {{- include "pterodactyl.labels" $ | nindent 4 }}
    app.kubernetes.io/component: wings
    app.kubernetes.io/instance-id: "{{ $index }}"
spec:
  type: ClusterIP
  selector:
    {{- include "pterodactyl.wings.selectorLabels" $ | nindent 4 }}
    # This targets the specific pod by name
    statefulset.kubernetes.io/pod-name: {{ include "pterodactyl.wings.name" $ }}-{{ $index }}
  ports:
    - name: http
      protocol: TCP
      port: 443
      targetPort: http
    - name: sftp
      protocol: TCP
      port: 2022
      targetPort: sftp
---
{{- end }}
{{- end }} 