{{- if .Values.wings.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pterodactyl.wings.name" . }}-gameservers
  namespace: {{ .Values.namespace | default "pterodactyl" }}
  labels:
    {{- include "pterodactyl.labels" . | nindent 4 }}
    app.kubernetes.io/component: wings-gameservers
spec:
  type: {{ .Values.gameServers.service.type }}
  # We need to expose a range of ports for game servers
  ports:
    {{- range seq (.Values.gameServers.service.portRange.start | int) (.Values.gameServers.service.portRange.end | int) | split " " }}
    - port: {{ . }}
      targetPort: {{ . }}
      protocol: TCP
      name: gs-{{ . }}
    - port: {{ . }}
      targetPort: {{ . }}
      protocol: UDP
      name: gs-udp-{{ . }}
    {{- end }}
  selector:
    {{- include "pterodactyl.wings.selectorLabels" . | nindent 4 }}
{{- end }} 