{{- if .Values.wings.enabled -}}
{{- if .Values.gameServers.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pterodactyl.wings.name" . }}-gameservers
  namespace: {{ .Values.namespace | default "pterodactyl" }}
  labels:
    {{- include "pterodactyl.labels" . | nindent 4 }}
    app.kubernetes.io/component: wings-gameservers
  {{- with .Values.gameServers.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gameServers.service.type }}
  {{- if .Values.gameServers.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.gameServers.service.loadBalancerIP }}
  {{- end }}
  # Auto-calculate ports from all Wings servers
  ports:
    {{- range .Values.wings.servers }}
    {{- range seq (.portRange.start | int) (.portRange.end | int) | split " " }}
    - port: {{ . }}
      targetPort: {{ . }}
      protocol: TCP
      name: gs-tcp-{{ . }}
    - port: {{ . }}
      targetPort: {{ . }}
      protocol: UDP
      name: gs-udp-{{ . }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "pterodactyl.labels" . | nindent 4 }}
    app.kubernetes.io/component: wings-proxy
{{- end }}
{{- end }} 