{{- if .Values.mysql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pterodactyl.mysql.name" . }}
  namespace: {{ .Values.namespace | default "pterodactyl" }}
  labels:
    {{- include "pterodactyl.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.rootPassword | b64enc }}
{{- end }} 