{{- if and .Values.mysql.enabled .Values.mysql.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pterodactyl.mysql.name" . }}
  labels:
    {{- include "pterodactyl.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  accessModes:
    {{- range .Values.mysql.persistence.accessModes }}
    - {{ . }}
    {{- end }}
  {{- if .Values.mysql.persistence.storageClass }}
  storageClassName: {{ .Values.mysql.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
{{- end }} 