{{- if .Values.panel.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pterodactyl.panel.name" . }}-app
  namespace: {{ .Values.namespace | default "pterodactyl" }}
  labels:
    {{- include "pterodactyl.labels" . | nindent 4 }}
    app.kubernetes.io/component: panel
type: Opaque
data:
  app-key: {{ .Values.panel.appKey | default "base64:SomeRandomBase64EncodedKeyForPterodactylPanelApplication32Chars=" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pterodactyl.panel.name" . }}-db
  namespace: {{ .Values.namespace | default "pterodactyl" }}
  labels:
    {{- include "pterodactyl.labels" . | nindent 4 }}
    app.kubernetes.io/component: panel
type: Opaque
data:
  db-password: {{ .Values.panel.database.password | b64enc }}
{{- end }}

{{- if and .Values.panel.enabled .Values.panel.redis.password -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pterodactyl.panel.name" . }}-redis
  namespace: {{ .Values.namespace | default "pterodactyl" }}
  labels:
    {{- include "pterodactyl.labels" . | nindent 4 }}
    app.kubernetes.io/component: panel
type: Opaque
data:
  redis-password: {{ .Values.panel.redis.password | b64enc }}
{{- end }} 