{{- if and .Values.panel.enabled .Values.panel.ingress.enabled -}}
{{- $fullName := include "pterodactyl.panel.name" . -}}
{{- $svcPort := .Values.panel.service.port -}}
{{- if and .Values.panel.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.panel.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.panel.ingress.annotations "kubernetes.io/ingress.class" .Values.panel.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace | default "pterodactyl" }}
  labels:
    {{- include "pterodactyl.labels" . | nindent 4 }}
    app.kubernetes.io/component: panel
  {{- with .Values.panel.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.panel.ingress.className }}
  ingressClassName: {{ .Values.panel.ingress.className }}
  {{- end }}
  {{- if .Values.panel.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.global.panelUrl | quote }}
      secretName: {{ .Values.global.panelUrl }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.global.panelUrl | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
{{- end }} 