{{- if and .Values.panel.enabled .Values.panel.persistence.enabled (not .Values.panel.persistence.hostPath) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pterodactyl.panel.name" . }}
  namespace: {{ .Values.namespace | default "pterodactyl" }}
  labels:
    {{- include "pterodactyl.labels" . | nindent 4 }}
    app.kubernetes.io/component: panel
spec:
  accessModes:
    {{- range .Values.panel.persistence.accessModes }}
    - {{ . }}
    {{- end }}
  {{- if .Values.panel.persistence.storageClass }}
  storageClassName: {{ .Values.panel.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.panel.persistence.size }}
{{- end }} 