{{- if .Values.panel.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pterodactyl.panel.name" . }}-db
  labels:
    {{- include "pterodactyl.labels" . | nindent 4 }}
    app.kubernetes.io/component: panel
type: Opaque
data:
  db-password: {{ .Values.panel.database.password | b64enc }}
{{- end }}

{{- if and .Values.panel.enabled .Values.panel.redis.password -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pterodactyl.panel.name" . }}-redis
  labels:
    {{- include "pterodactyl.labels" . | nindent 4 }}
    app.kubernetes.io/component: panel
type: Opaque
data:
  redis-password: {{ .Values.panel.redis.password | b64enc }}
{{- end }} 