{{- if .Values.panel.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pterodactyl.panel.name" . }}
  labels:
    {{- include "pterodactyl.labels" . | nindent 4 }}
    app.kubernetes.io/component: panel
spec:
  type: {{ .Values.panel.service.type }}
  ports:
    - port: {{ .Values.panel.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pterodactyl.panel.selectorLabels" . | nindent 4 }}
{{- end }} 