{{- if .Values.wings.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pterodactyl.wings.name" . }}
  namespace: {{ .Values.namespace | default "pterodactyl" }}
  labels:
    {{- include "pterodactyl.labels" . | nindent 4 }}
    app.kubernetes.io/component: wings
spec:
  type: {{ .Values.wings.service.type }}
  ports:
    - port: {{ .Values.wings.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 2022
      targetPort: sftp
      protocol: TCP
      name: sftp
  selector:
    {{- include "pterodactyl.wings.selectorLabels" . | nindent 4 }}
{{- end }} 