{{- if and .Values.wings.enabled .Values.wings.persistence.docker.enabled (not .Values.wings.persistence.docker.hostPath) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pterodactyl.wings.name" . }}-docker
  namespace: {{ .Values.namespace | default "pterodactyl" }}
  labels:
    {{- include "pterodactyl.labels" . | nindent 4 }}
    app.kubernetes.io/component: wings
spec:
  accessModes:
    {{- range .Values.wings.persistence.docker.accessModes }}
    - {{ . }}
    {{- end }}
  {{- if .Values.wings.persistence.docker.storageClass }}
  storageClassName: {{ .Values.wings.persistence.docker.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.wings.persistence.docker.size }}
{{- end }}

{{- if and .Values.wings.enabled .Values.wings.persistence.data.enabled (not .Values.wings.persistence.data.hostPath) -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pterodactyl.wings.name" . }}-data
  namespace: {{ .Values.namespace | default "pterodactyl" }}
  labels:
    {{- include "pterodactyl.labels" . | nindent 4 }}
    app.kubernetes.io/component: wings
spec:
  accessModes:
    {{- range .Values.wings.persistence.data.accessModes }}
    - {{ . }}
    {{- end }}
  {{- if .Values.wings.persistence.data.storageClass }}
  storageClassName: {{ .Values.wings.persistence.data.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.wings.persistence.data.size }}
{{- end }} 